# Generated by Django 4.1.7 on 2023-03-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(default=' ', max_length=20, null=True)),
                ('Loan_Selection', models.CharField(max_length=10)),
                ('Loan_Selection_edited', models.CharField(max_length=5)),
                ('Loan_Selection_user_edited', models.BinaryField()),
                ('Customer_Id', models.CharField(max_length=10)),
                ('Date_reported', models.DateField()),
                ('Loan_type', models.CharField(max_length=50)),
                ('Loan_status', models.CharField(max_length=10)),
                ('Disbursed_amount', models.CharField(max_length=20)),
                ('Disbursed_amount_edited', models.CharField(max_length=10, null=True)),
                ('Disbursed_amount_user_edited', models.CharField(max_length=10)),
                ('Disbursal_date', models.DateField()),
                ('Tenure', models.CharField(max_length=20, null=True)),
                ('Tenure_new', models.CharField(max_length=20, null=True)),
                ('Tenure_edited', models.CharField(max_length=20, null=True)),
                ('Tenure_user_edited', models.BinaryField()),
                ('ROI', models.CharField(max_length=10, null=True)),
                ('ROI_new', models.CharField(max_length=50, null=True)),
                ('ROI_edited', models.CharField(max_length=50, null=True)),
                ('ROI_user_edited', models.BinaryField()),
                ('EMI', models.CharField(blank=True, max_length=50, null=True)),
                ('EMI_new', models.CharField(blank=True, max_length=50, null=True)),
                ('EMI_edited', models.CharField(blank=True, max_length=50, null=True)),
                ('EMI_user_edited', models.BinaryField()),
                ('Current_Balance', models.CharField(blank=True, max_length=50)),
                ('DPD', models.CharField(blank=True, max_length=20, null=True)),
                ('DPD_month_new', models.CharField(blank=True, max_length=50, null=True)),
                ('Overdueamount', models.CharField(blank=True, max_length=20)),
                ('Source', models.CharField(max_length=20)),
                ('lead_id', models.CharField(blank=True, max_length=20, null=True)),
                ('final_selected', models.BinaryField()),
                ('valuetype', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
            ],
        ),
    ]
