# Generated by Django 4.1.3 on 2022-12-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bureau',
            fields=[
                ('index', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Loan_Selection', models.CharField(max_length=10)),
                ('Loan_Selection_edited', models.CharField(max_length=5)),
                ('Loan_Selection_user_edited', models.BinaryField()),
                ('Customer_Id', models.CharField(max_length=10)),
                ('Date_reported', models.DateField()),
                ('Loan_type', models.CharField(max_length=50)),
                ('Loan_status', models.CharField(max_length=10)),
                ('Disbursed_amount', models.CharField(max_length=20)),
                ('Disbursed_amount_edited', models.CharField(max_length=10, null=True)),
                ('Disbursed_amount_user_edited', models.CharField(max_length=10)),
                ('Disbursal_date', models.DateField()),
                ('Tenure', models.CharField(max_length=20, null=True)),
                ('Tenure_new', models.CharField(max_length=20, null=True)),
                ('Tenure_edited', models.CharField(max_length=20, null=True)),
                ('Tenure_user_edited', models.BinaryField()),
                ('ROI', models.CharField(max_length=10, null=True)),
                ('ROI_new', models.CharField(max_length=50, null=True)),
                ('ROI_edited', models.CharField(max_length=50, null=True)),
                ('ROI_user_edited', models.BinaryField()),
                ('EMI', models.CharField(blank=True, max_length=50, null=True)),
                ('EMI_new', models.CharField(blank=True, max_length=50, null=True)),
                ('EMI_edited', models.CharField(blank=True, max_length=50, null=True)),
                ('EMI_user_edited', models.BinaryField()),
                ('Current_Balance', models.CharField(blank=True, max_length=50)),
                ('DPD', models.CharField(blank=True, max_length=20, null=True)),
                ('DPD_month_new', models.DateField(blank=True, null=True)),
                ('Overdueamount', models.CharField(blank=True, max_length=20)),
                ('Source', models.CharField(max_length=20)),
                ('lead_id', models.CharField(blank=True, max_length=20, null=True)),
                ('final_selected', models.BinaryField()),
                ('valuetype', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='digitized_file_status',
            fields=[
                ('lead_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=50, unique=True)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='downloaded_file_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='los_did_cid_generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=20)),
                ('deal_id', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('bank', models.CharField(blank=True, max_length=30)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('creation_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='upload_file_details',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('tax_deposited', models.CharField(max_length=20)),
                ('bsr_code', models.CharField(max_length=20)),
                ('tax_deposited_date', models.DateField()),
                ('challan_serial_no', models.CharField(max_length=20)),
                ('status_math_oltas', models.CharField(max_length=20)),
                ('deal_id', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=20)),
                ('creation_time', models.TimeField()),
                ('last_modification_time', models.TimeField()),
                ('created_by_id', models.CharField(max_length=20)),
                ('last_modified_by_id', models.CharField(max_length=20)),
                ('assessment_year', models.DateField()),
                ('pan_of_the_employee', models.CharField(max_length=20)),
                ('lid', models.CharField(max_length=20)),
            ],
        ),
    ]
