# Generated by Django 4.1.3 on 2022-12-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaded_file_details',
            name='date',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='downloaded_file_details',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='downloaded_file_details',
            name='lead_id',
            field=models.CharField(max_length=200),
        ),
    ]
