# Generated by Django 4.1.3 on 2022-12-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_bureau_dpd_month_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bureau',
        ),
    ]
