# Generated by Django 4.1.3 on 2022-12-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_bureau'),
    ]

    operations = [
        migrations.DeleteModel(
            name='downloaded_file_details',
        ),
    ]
