# Generated by Django 4.1.3 on 2022-12-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_delete_downloaded_file_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloaded_file_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=500)),
            ],
        ),
    ]
