# Generated by Django 4.1.4 on 2022-12-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_downloaded_file_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('txn_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('debit', models.CharField(max_length=20)),
                ('credit', models.CharField(max_length=20)),
                ('balance', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=30)),
                ('deal_id', models.CharField(max_length=10)),
                ('customer_id', models.CharField(max_length=10)),
                ('creation_time', models.CharField(max_length=10)),
                ('last_modification_time', models.DateTimeField()),
                ('created_by_id', models.DateTimeField()),
                ('last_modified_by_id', models.CharField(max_length=10, null=True)),
                ('image_name', models.CharField(max_length=20)),
                ('cheque_number', models.CharField(max_length=30)),
                ('entity', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=20)),
                ('source_of_trans', models.CharField(max_length=20)),
                ('sub_mode', models.CharField(max_length=30)),
                ('transaction_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='los_lid_generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('aadhar', models.CharField(blank=True, max_length=2)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pin_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=50)),
                ('account', models.CharField(blank=True, max_length=30)),
                ('creation_time', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='upload_file_details',
            old_name='id',
            new_name='lead_id',
        ),
        migrations.RenameField(
            model_name='upload_file_details',
            old_name='bsr_code',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='upload_file_details',
            old_name='challan_serial_no',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='upload_file_details',
            name='assessment_year',
        ),
        migrations.RemoveField(
            model_name='upload_file_details',
            name='created_by_id',
        ),
        migrations.RemoveField(
            model_name='upload_file_details',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='upload_file_details',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='upload_file_details',
            name='deal_id',
        ),
        migrations.RemoveField(
            model_name='upload_file_details',
            name='last_modification_time',
        ),
        migrations.RemoveField(
            model_name='upload_file_details',
            name='last_modified_by_id',
        ),
        migrations.RemoveField(
            model_name='upload_file_details',
            name='lid',
        ),
        migrations.RemoveField(
            model_name='upload_file_details',
            name='pan_of_the_employee',
        ),
        migrations.RemoveField(
            model_name='upload_file_details',
            name='status_math_oltas',
        ),
        migrations.RemoveField(
            model_name='upload_file_details',
            name='tax_deposited',
        ),
        migrations.RemoveField(
            model_name='upload_file_details',
            name='tax_deposited_date',
        ),
        migrations.AddField(
            model_name='upload_file_details',
            name='date',
            field=models.DateTimeField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='upload_file_details',
            name='file_name',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
    ]
