# Generated by Django 4.1.4 on 2022-12-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_bank_bank_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file_details',
            name='id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upload_file_details',
            name='lead_id',
            field=models.CharField(max_length=30),
        ),
    ]
