# Generated by Django 4.1.4 on 2022-12-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_upload_file_details_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file_details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
