# Generated by Django 4.1.4 on 2023-01-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_bureau_account_segment_tl_customer_allocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bank_bank',
        ),
        migrations.DeleteModel(
            name='bureau_account_segment_tl',
        ),
        migrations.DeleteModel(
            name='los_lid_generation',
        ),
    ]
