# Generated by Django 4.1.4 on 2023-01-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_delete_bank_bank_delete_bureau_account_segment_tl_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload_file_details',
        ),
    ]
