# Generated by Django 4.1.7 on 2023-03-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_bank_bank_bureau_account_segment_tl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='recieved_file_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=255)),
                ('scanned', models.BooleanField()),
                ('uploaded_output', models.FileField(upload_to='uploads/')),
                ('uploaded_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
