# Generated by Django 4.1.7 on 2023-03-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_recieved_file_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file_details',
            name='id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
